/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */

export interface DtoAnalyzeYoutubeRequest {
  /**
     * @minimum 5
     * @maximum 120
     */
  segment_duration?: number;
  /** @minimum 0 */
  segment_start?: number;
  url: string;
}
