/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */
import type { DtoCandidateResponse } from './dtoCandidateResponse';

export interface DtoAnalysisDetailResponse {
  audio_quality?: string;
  candidates?: DtoCandidateResponse[];
  completed_at?: string;
  confidence_label?: string;
  confidence_score?: number;
  created_at?: string;
  detected_maqam_id?: string;
  error_code?: string;
  error_message?: string;
  explanation_text?: string;
  id?: string;
  input_source?: string;
  input_type?: string;
  processing_ms?: number;
  status?: string;
}
