/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */

export interface DtoCreateUserRequest {
  address: string;
  /** @maxLength 100 */
  email: string;
  /**
     * @minLength 3
     * @maxLength 100
     */
  full_name: string;
  /**
     * @minLength 6
     * @maxLength 100
     */
  password: string;
  /** @maxLength 15 */
  phone: string;
  /**
     * @minLength 3
     * @maxLength 50
     */
  username: string;
}
