/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Starter Kit API
 * Ini adalah API starter kit menggunakan Echo Go.
 * OpenAPI spec version: 1.0
 */

export interface DtoCreateUserRequest {
  address: string;
  email: string;
  /** @minLength 3 */
  full_name: string;
  /** @minLength 6 */
  password: string;
  phone: string;
  /** @minLength 3 */
  username: string;
}
