/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */

export interface DtoHistoryItemResponse {
  confidence_score?: number;
  created_at?: string;
  detected_maqam_id?: string;
  id?: string;
  input_source?: string;
  input_type?: string;
  maqam_name_latin?: string;
  status?: string;
}
