/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Starter Kit API
 * Ini adalah API starter kit menggunakan Echo Go.
 * OpenAPI spec version: 1.0
 */

export interface DtoLoginUserResponse {
  token?: string;
}
