/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */

export interface DtoMaqamDetailResponse {
  emotion_tags?: string[];
  example_songs?: string[];
  id?: string;
  interval_description?: string;
  name_arabic?: string;
  name_indonesia?: string;
  name_latin?: string;
  tips_aransemen?: string;
}
