/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */

export type GetHistoryParams = {
/**
 * Halaman
 */
page?: number;
/**
 * Jumlah per halaman
 */
limit?: number;
};
