/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */

export * from './dtoAnalysisDetailResponse';
export * from './dtoAnalyzeAcceptedResponse';
export * from './dtoAnalyzeYoutubeRequest';
export * from './dtoCandidateResponse';
export * from './dtoCreateUserRequest';
export * from './dtoErrorResponse';
export * from './dtoHistoryItemResponse';
export * from './dtoHistoryListResponse';
export * from './dtoLoginUserRequest';
export * from './dtoLoginUserResponse';
export * from './dtoMaqamDetailResponse';
export * from './dtoMaqamListResponse';
export * from './dtoPaginationMeta';
export * from './dtoSuccessResponse';
export * from './getHistoryParams';
export * from './postAnalyzeRecordBody';
export * from './postAnalyzeUploadBody';
