// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Anas (Cypress Consulting)"
        },
        "license": {
            "name": "ISC"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analyses/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Ambil status/hasil analisis (polling)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "X-Session-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Analysis UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AnalysisDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analyze/record": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Analisis maqam dari rekaman mikrofon/humming",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "X-Session-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Audio recording",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "microphone",
                        "description": "Mode: microphone atau humming",
                        "name": "mode",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dto.AnalyzeAcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analyze/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Analisis maqam dari file audio upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "X-Session-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File audio (WAV, MP3, M4A, dll.)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dto.AnalyzeAcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analyze/youtube": {
            "post": {
                "description": "Memulai proses analisis maqam dari video YouTube secara asinkron",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Analisis maqam dari YouTube URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "X-Session-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "YouTube analysis request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AnalyzeYoutubeRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dto.AnalyzeAcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Riwayat analisis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "X-Session-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Jumlah per halaman",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HistoryListResponse"
                        }
                    }
                }
            }
        },
        "/history/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Hapus riwayat analisis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "X-Session-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Analysis UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/maqamat": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maqam"
                ],
                "summary": "Daftar semua maqam yang didukung",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.MaqamListResponse"
                            }
                        }
                    }
                }
            }
        },
        "/maqamat/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maqam"
                ],
                "summary": "Detail maqam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Maqam ID (e.g. hijaz)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MaqamDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get current logged in user profile based on JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Create a new user with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AnalysisDetailResponse": {
            "type": "object",
            "properties": {
                "audio_quality": {
                    "type": "string",
                    "example": "good"
                },
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CandidateResponse"
                    }
                },
                "completed_at": {
                    "type": "string"
                },
                "confidence_label": {
                    "type": "string",
                    "example": "tinggi"
                },
                "confidence_score": {
                    "type": "number",
                    "example": 0.87
                },
                "created_at": {
                    "type": "string"
                },
                "detected_maqam_id": {
                    "type": "string",
                    "example": "hijaz"
                },
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "explanation_text": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input_source": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=..."
                },
                "input_type": {
                    "type": "string",
                    "example": "youtube"
                },
                "processing_ms": {
                    "type": "integer",
                    "example": 12500
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "dto.AnalyzeAcceptedResponse": {
            "type": "object",
            "properties": {
                "analysis_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "estimated_seconds": {
                    "type": "integer",
                    "example": 30
                },
                "polling_url": {
                    "type": "string",
                    "example": "/api/v1/analyses/550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "dto.AnalyzeYoutubeRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "segment_duration": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 5,
                    "example": 60
                },
                "segment_start": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "url": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                }
            }
        },
        "dto.CandidateResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number",
                    "example": 0.87
                },
                "maqam_id": {
                    "type": "string",
                    "example": "hijaz"
                },
                "name_arabic": {
                    "type": "string",
                    "example": "حجاز"
                },
                "name_latin": {
                    "type": "string",
                    "example": "Hijaz"
                },
                "rank": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "required": [
                "address",
                "email",
                "full_name",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "maxLength": 100
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 6
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "dto.HistoryItemResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "detected_maqam_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input_source": {
                    "type": "string"
                },
                "input_type": {
                    "type": "string",
                    "example": "youtube"
                },
                "maqam_name_latin": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.HistoryListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HistoryItemResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.PaginationMeta"
                }
            }
        },
        "dto.LoginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginUserResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.MaqamDetailResponse": {
            "type": "object",
            "properties": {
                "emotion_tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "example_songs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "interval_description": {
                    "type": "string"
                },
                "name_arabic": {
                    "type": "string"
                },
                "name_indonesia": {
                    "type": "string"
                },
                "name_latin": {
                    "type": "string"
                },
                "tips_aransemen": {
                    "type": "string"
                }
            }
        },
        "dto.MaqamListResponse": {
            "type": "object",
            "properties": {
                "emotion_tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "hijaz"
                },
                "interval_description": {
                    "type": "string",
                    "example": "D – E♭ – F♯ – G – A – B♭ – C"
                },
                "name_arabic": {
                    "type": "string",
                    "example": "حجاز"
                },
                "name_indonesia": {
                    "type": "string",
                    "example": "Hijaz"
                },
                "name_latin": {
                    "type": "string",
                    "example": "Hijaz"
                }
            }
        },
        "dto.PaginationMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total_items": {
                    "type": "integer",
                    "example": 42
                },
                "total_pages": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MaqamDetector API",
	Description:      "API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
