/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoAnalysisDetailResponse,
  DtoAnalyzeAcceptedResponse,
  DtoAnalyzeYoutubeRequest,
  DtoErrorResponse,
  PostAnalyzeRecordBody,
  PostAnalyzeUploadBody
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getAnalysesIdResponse200 = {
  data: DtoAnalysisDetailResponse
  status: 200
}

export type getAnalysesIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getAnalysesIdResponseSuccess = (getAnalysesIdResponse200) & {
  headers: Headers;
};
export type getAnalysesIdResponseError = (getAnalysesIdResponse404) & {
  headers: Headers;
};

export type getAnalysesIdResponse = (getAnalysesIdResponseSuccess | getAnalysesIdResponseError)

export const getGetAnalysesIdUrl = (id: string,) => {




  return `/analyses/${id}`
}

/**
 * @summary Ambil status/hasil analisis (polling)
 */
export const getAnalysesId = async (id: string, options?: RequestInit): Promise<getAnalysesIdResponse> => {

  return customInstance<getAnalysesIdResponse>(getGetAnalysesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAnalysesIdQueryKey = (id: string,) => {
    return [
    `/analyses/${id}`
    ] as const;
    }


export const getGetAnalysesIdQueryOptions = <TData = Awaited<ReturnType<typeof getAnalysesId>>, TError = DtoErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalysesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalysesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalysesId>>> = ({ signal }) => getAnalysesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalysesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalysesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalysesId>>>
export type GetAnalysesIdQueryError = DtoErrorResponse


export function useGetAnalysesId<TData = Awaited<ReturnType<typeof getAnalysesId>>, TError = DtoErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalysesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalysesId>>,
          TError,
          Awaited<ReturnType<typeof getAnalysesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalysesId<TData = Awaited<ReturnType<typeof getAnalysesId>>, TError = DtoErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalysesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalysesId>>,
          TError,
          Awaited<ReturnType<typeof getAnalysesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalysesId<TData = Awaited<ReturnType<typeof getAnalysesId>>, TError = DtoErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalysesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ambil status/hasil analisis (polling)
 */

export function useGetAnalysesId<TData = Awaited<ReturnType<typeof getAnalysesId>>, TError = DtoErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalysesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalysesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postAnalyzeRecordResponse202 = {
  data: DtoAnalyzeAcceptedResponse
  status: 202
}

export type postAnalyzeRecordResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAnalyzeRecordResponseSuccess = (postAnalyzeRecordResponse202) & {
  headers: Headers;
};
export type postAnalyzeRecordResponseError = (postAnalyzeRecordResponse400) & {
  headers: Headers;
};

export type postAnalyzeRecordResponse = (postAnalyzeRecordResponseSuccess | postAnalyzeRecordResponseError)

export const getPostAnalyzeRecordUrl = () => {




  return `/analyze/record`
}

/**
 * @summary Analisis maqam dari rekaman mikrofon/humming
 */
export const postAnalyzeRecord = async (postAnalyzeRecordBody?: PostAnalyzeRecordBody, options?: RequestInit): Promise<postAnalyzeRecordResponse> => {
    const formData = new FormData();
if(postAnalyzeRecordBody?.file !== undefined) {
 formData.append(`file`, postAnalyzeRecordBody.file);
 }
if(postAnalyzeRecordBody?.mode !== undefined) {
 formData.append(`mode`, postAnalyzeRecordBody.mode);
 }

  return customInstance<postAnalyzeRecordResponse>(getPostAnalyzeRecordUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getPostAnalyzeRecordMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeRecord>>, TError,{data?: PostAnalyzeRecordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeRecord>>, TError,{data?: PostAnalyzeRecordBody}, TContext> => {

const mutationKey = ['postAnalyzeRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAnalyzeRecord>>, {data?: PostAnalyzeRecordBody}> = (props) => {
          const {data} = props ?? {};

          return  postAnalyzeRecord(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAnalyzeRecordMutationResult = NonNullable<Awaited<ReturnType<typeof postAnalyzeRecord>>>
    export type PostAnalyzeRecordMutationBody = PostAnalyzeRecordBody | undefined
    export type PostAnalyzeRecordMutationError = DtoErrorResponse

    /**
 * @summary Analisis maqam dari rekaman mikrofon/humming
 */
export const usePostAnalyzeRecord = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeRecord>>, TError,{data?: PostAnalyzeRecordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAnalyzeRecord>>,
        TError,
        {data?: PostAnalyzeRecordBody},
        TContext
      > => {
      return useMutation(getPostAnalyzeRecordMutationOptions(options), queryClient);
    }
    export type postAnalyzeUploadResponse202 = {
  data: DtoAnalyzeAcceptedResponse
  status: 202
}

export type postAnalyzeUploadResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAnalyzeUploadResponse413 = {
  data: DtoErrorResponse
  status: 413
}

export type postAnalyzeUploadResponseSuccess = (postAnalyzeUploadResponse202) & {
  headers: Headers;
};
export type postAnalyzeUploadResponseError = (postAnalyzeUploadResponse400 | postAnalyzeUploadResponse413) & {
  headers: Headers;
};

export type postAnalyzeUploadResponse = (postAnalyzeUploadResponseSuccess | postAnalyzeUploadResponseError)

export const getPostAnalyzeUploadUrl = () => {




  return `/analyze/upload`
}

/**
 * @summary Analisis maqam dari file audio upload
 */
export const postAnalyzeUpload = async (postAnalyzeUploadBody?: PostAnalyzeUploadBody, options?: RequestInit): Promise<postAnalyzeUploadResponse> => {
    const formData = new FormData();
if(postAnalyzeUploadBody?.file !== undefined) {
 formData.append(`file`, postAnalyzeUploadBody.file);
 }

  return customInstance<postAnalyzeUploadResponse>(getPostAnalyzeUploadUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getPostAnalyzeUploadMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeUpload>>, TError,{data?: PostAnalyzeUploadBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeUpload>>, TError,{data?: PostAnalyzeUploadBody}, TContext> => {

const mutationKey = ['postAnalyzeUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAnalyzeUpload>>, {data?: PostAnalyzeUploadBody}> = (props) => {
          const {data} = props ?? {};

          return  postAnalyzeUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAnalyzeUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postAnalyzeUpload>>>
    export type PostAnalyzeUploadMutationBody = PostAnalyzeUploadBody | undefined
    export type PostAnalyzeUploadMutationError = DtoErrorResponse

    /**
 * @summary Analisis maqam dari file audio upload
 */
export const usePostAnalyzeUpload = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeUpload>>, TError,{data?: PostAnalyzeUploadBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAnalyzeUpload>>,
        TError,
        {data?: PostAnalyzeUploadBody},
        TContext
      > => {
      return useMutation(getPostAnalyzeUploadMutationOptions(options), queryClient);
    }
    export type postAnalyzeYoutubeResponse202 = {
  data: DtoAnalyzeAcceptedResponse
  status: 202
}

export type postAnalyzeYoutubeResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAnalyzeYoutubeResponse429 = {
  data: DtoErrorResponse
  status: 429
}

export type postAnalyzeYoutubeResponseSuccess = (postAnalyzeYoutubeResponse202) & {
  headers: Headers;
};
export type postAnalyzeYoutubeResponseError = (postAnalyzeYoutubeResponse400 | postAnalyzeYoutubeResponse429) & {
  headers: Headers;
};

export type postAnalyzeYoutubeResponse = (postAnalyzeYoutubeResponseSuccess | postAnalyzeYoutubeResponseError)

export const getPostAnalyzeYoutubeUrl = () => {




  return `/analyze/youtube`
}

/**
 * Memulai proses analisis maqam dari video YouTube secara asinkron
 * @summary Analisis maqam dari YouTube URL
 */
export const postAnalyzeYoutube = async (dtoAnalyzeYoutubeRequest: DtoAnalyzeYoutubeRequest, options?: RequestInit): Promise<postAnalyzeYoutubeResponse> => {

  return customInstance<postAnalyzeYoutubeResponse>(getPostAnalyzeYoutubeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoAnalyzeYoutubeRequest,)
  }
);}




export const getPostAnalyzeYoutubeMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeYoutube>>, TError,{data: DtoAnalyzeYoutubeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeYoutube>>, TError,{data: DtoAnalyzeYoutubeRequest}, TContext> => {

const mutationKey = ['postAnalyzeYoutube'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAnalyzeYoutube>>, {data: DtoAnalyzeYoutubeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAnalyzeYoutube(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAnalyzeYoutubeMutationResult = NonNullable<Awaited<ReturnType<typeof postAnalyzeYoutube>>>
    export type PostAnalyzeYoutubeMutationBody = DtoAnalyzeYoutubeRequest
    export type PostAnalyzeYoutubeMutationError = DtoErrorResponse

    /**
 * @summary Analisis maqam dari YouTube URL
 */
export const usePostAnalyzeYoutube = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnalyzeYoutube>>, TError,{data: DtoAnalyzeYoutubeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAnalyzeYoutube>>,
        TError,
        {data: DtoAnalyzeYoutubeRequest},
        TContext
      > => {
      return useMutation(getPostAnalyzeYoutubeMutationOptions(options), queryClient);
    }
