/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoErrorResponse,
  DtoMaqamDetailResponse,
  DtoMaqamListResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getMaqamatResponse200 = {
  data: DtoMaqamListResponse[]
  status: 200
}

export type getMaqamatResponseSuccess = (getMaqamatResponse200) & {
  headers: Headers;
};
;

export type getMaqamatResponse = (getMaqamatResponseSuccess)

export const getGetMaqamatUrl = () => {




  return `/maqamat`
}

/**
 * @summary Daftar semua maqam yang didukung
 */
export const getMaqamat = async ( options?: RequestInit): Promise<getMaqamatResponse> => {

  return customInstance<getMaqamatResponse>(getGetMaqamatUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMaqamatQueryKey = () => {
    return [
    `/maqamat`
    ] as const;
    }


export const getGetMaqamatQueryOptions = <TData = Awaited<ReturnType<typeof getMaqamat>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMaqamatQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMaqamat>>> = ({ signal }) => getMaqamat({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMaqamat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMaqamatQueryResult = NonNullable<Awaited<ReturnType<typeof getMaqamat>>>
export type GetMaqamatQueryError = unknown


export function useGetMaqamat<TData = Awaited<ReturnType<typeof getMaqamat>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaqamat>>,
          TError,
          Awaited<ReturnType<typeof getMaqamat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaqamat<TData = Awaited<ReturnType<typeof getMaqamat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaqamat>>,
          TError,
          Awaited<ReturnType<typeof getMaqamat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaqamat<TData = Awaited<ReturnType<typeof getMaqamat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Daftar semua maqam yang didukung
 */

export function useGetMaqamat<TData = Awaited<ReturnType<typeof getMaqamat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMaqamatQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getMaqamatIdResponse200 = {
  data: DtoMaqamDetailResponse
  status: 200
}

export type getMaqamatIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getMaqamatIdResponseSuccess = (getMaqamatIdResponse200) & {
  headers: Headers;
};
export type getMaqamatIdResponseError = (getMaqamatIdResponse404) & {
  headers: Headers;
};

export type getMaqamatIdResponse = (getMaqamatIdResponseSuccess | getMaqamatIdResponseError)

export const getGetMaqamatIdUrl = (id: string,) => {




  return `/maqamat/${id}`
}

/**
 * @summary Detail maqam
 */
export const getMaqamatId = async (id: string, options?: RequestInit): Promise<getMaqamatIdResponse> => {

  return customInstance<getMaqamatIdResponse>(getGetMaqamatIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMaqamatIdQueryKey = (id: string,) => {
    return [
    `/maqamat/${id}`
    ] as const;
    }


export const getGetMaqamatIdQueryOptions = <TData = Awaited<ReturnType<typeof getMaqamatId>>, TError = DtoErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamatId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMaqamatIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMaqamatId>>> = ({ signal }) => getMaqamatId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMaqamatId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMaqamatIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMaqamatId>>>
export type GetMaqamatIdQueryError = DtoErrorResponse


export function useGetMaqamatId<TData = Awaited<ReturnType<typeof getMaqamatId>>, TError = DtoErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamatId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaqamatId>>,
          TError,
          Awaited<ReturnType<typeof getMaqamatId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaqamatId<TData = Awaited<ReturnType<typeof getMaqamatId>>, TError = DtoErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamatId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaqamatId>>,
          TError,
          Awaited<ReturnType<typeof getMaqamatId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaqamatId<TData = Awaited<ReturnType<typeof getMaqamatId>>, TError = DtoErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamatId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Detail maqam
 */

export function useGetMaqamatId<TData = Awaited<ReturnType<typeof getMaqamatId>>, TError = DtoErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaqamatId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMaqamatIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






