/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Starter Kit API
 * Ini adalah API starter kit menggunakan Echo Go.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoCreateUserRequest,
  DtoErrorResponse,
  DtoLoginUserRequest,
  DtoLoginUserResponse,
  DtoSuccessResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getUsersResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getUsersResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getUsersResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
export type getUsersResponseError = (getUsersResponse401 | getUsersResponse404) & {
  headers: Headers;
};

export type getUsersResponse = (getUsersResponseSuccess | getUsersResponseError)

export const getGetUsersUrl = () => {




  return `/users`
}

/**
 * Get current logged in user profile based on JWT token
 * @summary Get user profile
 */
export const getUsers = async ( options?: RequestInit): Promise<getUsersResponse> => {

  return customInstance<getUsersResponse>(getGetUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersQueryKey = () => {
    return [
    `/users`
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = DtoErrorResponse


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user profile
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postUsersLoginResponse200 = {
  data: DtoLoginUserResponse
  status: 200
}

export type postUsersLoginResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postUsersLoginResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postUsersLoginResponseSuccess = (postUsersLoginResponse200) & {
  headers: Headers;
};
export type postUsersLoginResponseError = (postUsersLoginResponse400 | postUsersLoginResponse401) & {
  headers: Headers;
};

export type postUsersLoginResponse = (postUsersLoginResponseSuccess | postUsersLoginResponseError)

export const getPostUsersLoginUrl = () => {




  return `/users/login`
}

/**
 * Authenticate user and return JWT token
 * @summary Login user
 */
export const postUsersLogin = async (dtoLoginUserRequest: DtoLoginUserRequest, options?: RequestInit): Promise<postUsersLoginResponse> => {

  return customInstance<postUsersLoginResponse>(getPostUsersLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoLoginUserRequest,)
  }
);}




export const getPostUsersLoginMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersLogin>>, TError,{data: DtoLoginUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsersLogin>>, TError,{data: DtoLoginUserRequest}, TContext> => {

const mutationKey = ['postUsersLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersLogin>>, {data: DtoLoginUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postUsersLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersLogin>>>
    export type PostUsersLoginMutationBody = DtoLoginUserRequest
    export type PostUsersLoginMutationError = DtoErrorResponse

    /**
 * @summary Login user
 */
export const usePostUsersLogin = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersLogin>>, TError,{data: DtoLoginUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersLogin>>,
        TError,
        {data: DtoLoginUserRequest},
        TContext
      > => {
      return useMutation(getPostUsersLoginMutationOptions(options), queryClient);
    }
    export type postUsersRegisterResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postUsersRegisterResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postUsersRegisterResponseSuccess = (postUsersRegisterResponse201) & {
  headers: Headers;
};
export type postUsersRegisterResponseError = (postUsersRegisterResponse400) & {
  headers: Headers;
};

export type postUsersRegisterResponse = (postUsersRegisterResponseSuccess | postUsersRegisterResponseError)

export const getPostUsersRegisterUrl = () => {




  return `/users/register`
}

/**
 * Create a new user with the provided details
 * @summary Register new user
 */
export const postUsersRegister = async (dtoCreateUserRequest: DtoCreateUserRequest, options?: RequestInit): Promise<postUsersRegisterResponse> => {

  return customInstance<postUsersRegisterResponse>(getPostUsersRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateUserRequest,)
  }
);}




export const getPostUsersRegisterMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersRegister>>, TError,{data: DtoCreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsersRegister>>, TError,{data: DtoCreateUserRequest}, TContext> => {

const mutationKey = ['postUsersRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersRegister>>, {data: DtoCreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postUsersRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersRegister>>>
    export type PostUsersRegisterMutationBody = DtoCreateUserRequest
    export type PostUsersRegisterMutationError = DtoErrorResponse

    /**
 * @summary Register new user
 */
export const usePostUsersRegister = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersRegister>>, TError,{data: DtoCreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersRegister>>,
        TError,
        {data: DtoCreateUserRequest},
        TContext
      > => {
      return useMutation(getPostUsersRegisterMutationOptions(options), queryClient);
    }
