/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * MaqamDetector API
 * API pendeteksi maqam musik Arab & Timur Tengah untuk komunitas banjari.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoErrorResponse,
  DtoHistoryListResponse,
  DtoSuccessResponse,
  GetHistoryParams
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getHistoryResponse200 = {
  data: DtoHistoryListResponse
  status: 200
}

export type getHistoryResponseSuccess = (getHistoryResponse200) & {
  headers: Headers;
};
;

export type getHistoryResponse = (getHistoryResponseSuccess)

export const getGetHistoryUrl = (params?: GetHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/history?${stringifiedParams}` : `/history`
}

/**
 * @summary Riwayat analisis
 */
export const getHistory = async (params?: GetHistoryParams, options?: RequestInit): Promise<getHistoryResponse> => {

  return customInstance<getHistoryResponse>(getGetHistoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHistoryQueryKey = (params?: GetHistoryParams,) => {
    return [
    `/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({ signal }) => getHistory(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getHistory>>>
export type GetHistoryQueryError = unknown


export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: undefined |  GetHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Riwayat analisis
 */

export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteHistoryIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteHistoryIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteHistoryIdResponseSuccess = (deleteHistoryIdResponse200) & {
  headers: Headers;
};
export type deleteHistoryIdResponseError = (deleteHistoryIdResponse404) & {
  headers: Headers;
};

export type deleteHistoryIdResponse = (deleteHistoryIdResponseSuccess | deleteHistoryIdResponseError)

export const getDeleteHistoryIdUrl = (id: string,) => {




  return `/history/${id}`
}

/**
 * @summary Hapus riwayat analisis
 */
export const deleteHistoryId = async (id: string, options?: RequestInit): Promise<deleteHistoryIdResponse> => {

  return customInstance<deleteHistoryIdResponse>(getDeleteHistoryIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteHistoryIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteHistoryId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteHistoryId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteHistoryId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteHistoryId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteHistoryId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteHistoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteHistoryId>>>

    export type DeleteHistoryIdMutationError = DtoErrorResponse

    /**
 * @summary Hapus riwayat analisis
 */
export const useDeleteHistoryId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteHistoryId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteHistoryId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteHistoryIdMutationOptions(options), queryClient);
    }
